package cmd

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	gh "github.com/maxbeizer/gh-fleet/internal/github"
)

func runCatalog(args []string) error {
	fs := flag.NewFlagSet("catalog", flag.ContinueOnError)
	configDir := fs.String("config", ".", "directory containing fleet.toml")
	if err := fs.Parse(args); err != nil {
		return err
	}

	cfg, err := loadConfig(*configDir)
	if err != nil {
		return err
	}

	fmt.Fprintf(os.Stderr, "Discovering extensions for %s...\n", cfg.Owner)
	repos, err := gh.ListGHRepos(cfg.Owner)
	if err != nil {
		return err
	}

	// Filter excluded and archived
	var filtered []gh.Repo
	for _, r := range repos {
		if cfg.IsExcluded(r.Name) || r.IsArchived {
			continue
		}
		filtered = append(filtered, r)
	}

	fmt.Fprintf(os.Stderr, "Found %d extensions, fetching Go versions...\n", len(filtered))
	gh.FetchGoVersions(cfg.Owner, filtered)

	sort.Slice(filtered, func(i, j int) bool {
		return filtered[i].Name < filtered[j].Name
	})

	// Build markdown
	var sb strings.Builder

	// Header
	if cfg.Catalog.Header != "" {
		headerPath := filepath.Join(cfg.Dir, cfg.Catalog.Header)
		header, err := os.ReadFile(headerPath)
		if err == nil {
			sb.Write(header)
			sb.WriteString("\n")
		}
	}

	sb.WriteString("## Extensions\n\n")
	sb.WriteString("| Extension | Description | Language | Go | Stars | Install |\n")
	sb.WriteString("|-----------|-------------|----------|----|-------|---------|\n")

	for _, r := range filtered {
		desc := r.Description
		if len(desc) > 60 {
			desc = desc[:57] + "..."
		}
		goVer := r.GoVersion
		if goVer == "" {
			goVer = "—"
		}
		lang := r.PrimaryLanguage
		if lang == "" {
			lang = "—"
		}
		sb.WriteString(fmt.Sprintf("| [%s](%s) | %s | %s | %s | ⭐%d | `gh ext install %s/%s` |\n",
			r.Name, r.URL, desc, lang, goVer, r.Stars, cfg.Owner, r.Name))
	}

	sb.WriteString(fmt.Sprintf("\n---\n\n*Catalog generated by [gh-fleet](https://github.com/%s/gh-fleet) on %s.*\n",
		cfg.Owner, time.Now().Format("2006-01-02")))

	output := cfg.Catalog.Output
	if output == "" {
		output = "README.md"
	}
	outputPath := filepath.Join(cfg.Dir, output)

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing catalog: %w", err)
	}

	fmt.Fprintf(os.Stderr, "✅ Wrote catalog to %s (%d extensions)\n", output, len(filtered))
	return nil
}
